#!/usr/bin/sh

docker exec -d ${PWD##*/}-wordpress-1 find -name "*_archive.zip" -type f -delete
docker exec -d ${PWD##*/}-wordpress-1 find -name "*installer.php" -type f -delete
docker exec -d ${PWD##*/}-wordpress-1 find -name "*.sql" -type f -delete
