#!/usr/bin/sh

echo "------------------------------------------------------------"
echo "Checking configuration"
echo "------------------------------------------------------------"

if [ ! -f ".env" ]; then
    cp .env.example .env
    echo "The .env file not found."
    echo "It has been copied for you. Please edit the file before continuing!"
    exit 1
fi

echo "------------------------------------------------------------"
echo "Installing WordPress"
echo "------------------------------------------------------------"

docker-compose up -d mysql phpmyadmin wordpress

echo "Waiting for WordPress to be installed ..."
sleep 20
until docker-compose run --rm wp-cli wp db check
do 
    echo "..."
    sleep 5
done

echo "------------------------------------------------------------"
echo "Configuring WordPress"
echo "------------------------------------------------------------"

docker-compose run --rm wp-cli sh -c 'sh /usr/local/bin/install-wp'

echo "------------------------------------------------------------"
echo "WordPress Ready!"
echo "------------------------------------------------------------"

cd src
npm install
npm run dev

echo "------------------------------------------------------------"
echo "FrontEnd Ready!"
echo "------------------------------------------------------------"