#!/usr/bin/sh

echo "------------------------------------------------------------"
echo "Deleting project"
echo "------------------------------------------------------------"

docker-compose down --volumes
